/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    publications: Publication;
    videos: Video;
    partners: Partner;
    programmes: Programme;
    'team-members': TeamMember;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-header': SiteHeader;
    'site-footer': SiteFooter;
    'contact-info': ContactInfo;
    'homepage-hero': HomepageHero;
  };
  globalsSelect: {
    'site-header': SiteHeaderSelect<false> | SiteHeaderSelect<true>;
    'site-footer': SiteFooterSelect<false> | SiteFooterSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'homepage-hero': HomepageHeroSelect<false> | HomepageHeroSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Articles d'actualité publiés par REACT ou agrégés depuis les sources externes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * URL-safe identifier — lowercase letters, digits, hyphens only.
   */
  slug: string;
  /**
   * 1-2 sentences. Shown in the news index card and as the meta description.
   */
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Catégorisation par secteur D012 (un seul par article).
   */
  sector:
    | 'digitalisation-technologie'
    | 'developpement-economique'
    | 'entrepreneuriat-local'
    | 'agroecologie'
    | 'energies-renouvelables'
    | 'multimedia'
    | 'transformation'
    | 'artisanat'
    | 'elevage'
    | 'saponification';
  writePath: 'react-original' | 'aggregated';
  /**
   * Lien d'origine pour les articles agrégés. Obligatoire quand writePath = aggregated.
   */
  sourceUrl?: string | null;
  publishedAt: string;
  /**
   * Optionnelle. Affichée en haut de l'article et dans la carte d'index.
   */
  coverImage?: (number | null) | Media;
  /**
   * Modération obligatoire (Phase 8). Décocher pour fermer les commentaires sur cet article.
   */
  commentsEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Publications téléchargeables — études, notes de réflexion, rapports REACT. Accès libre.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  slug: string;
  /**
   * Description courte affichée dans la liste et en méta-description.
   */
  summary: string;
  /**
   * PDF téléchargeable. Préférer < 5 MB pour les connexions mobiles ouest-africaines.
   */
  file: number | Media;
  coverImage?: (number | null) | Media;
  /**
   * Optionnel — laisser vide pour les publications transversales.
   */
  sector?:
    | (
        | 'digitalisation-technologie'
        | 'developpement-economique'
        | 'entrepreneuriat-local'
        | 'agroecologie'
        | 'energies-renouvelables'
        | 'multimedia'
        | 'transformation'
        | 'artisanat'
        | 'elevage'
        | 'saponification'
      )
    | null;
  /**
   * Premier auteur en haut de la liste.
   */
  authors?:
    | {
        name: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  language?: ('fr' | 'en' | 'wo') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Vidéos REACT et partenaires — capsules, témoignages, entretiens, vlogs. Sous-titres FR + Wolof.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  slug: string;
  summary: string;
  /**
   * Identifiant à 11 caractères extrait de l'URL YouTube. Exemple : pour https://youtube.com/watch?v=dQw4w9WgXcQ, l'ID est dQw4w9WgXcQ.
   */
  youtubeId: string;
  videoType: 'capsule' | 'explanation' | 'interview' | 'vlog' | 'testimonial';
  origin: 'react-original' | 'curated';
  sector?:
    | (
        | 'digitalisation-technologie'
        | 'developpement-economique'
        | 'entrepreneuriat-local'
        | 'agroecologie'
        | 'energies-renouvelables'
        | 'multimedia'
        | 'transformation'
        | 'artisanat'
        | 'elevage'
        | 'saponification'
      )
    | null;
  /**
   * Fichier .vtt facultatif. Si fourni, sera proposé par défaut sur le lecteur.
   */
  subtitlesFr?: (number | null) | Media;
  /**
   * Toutes les vidéos REACT-originales devraient avoir des sous-titres Wolof.
   */
  subtitlesWo?: (number | null) | Media;
  /**
   * Lien direct vers une copie téléchargeable de la vidéo (Drive, Dropbox, etc.) — pour les utilisateurs avec une connexion intermittente. Optionnel.
   */
  downloadUrl?: string | null;
  /**
   * Optionnel — affiché en mm:ss dans la liste.
   */
  duration?: number | null;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Partenaires institutionnels et société civile de REACT. Logos téléchargés via Media.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * Identifiant URL-safe — lettres minuscules, chiffres, tirets seulement.
   */
  slug: string;
  /**
   * Nom affiché tel que l'a écrit Amadou. Pas de tri alphabétique imposé.
   */
  name: string;
  kind: 'institution' | 'ngo';
  /**
   * Une phrase, FR. Décrit la catégorie ou le rôle — éviter les spécificités non confirmées par Amadou.
   */
  description: string;
  /**
   * Ordre d'affichage dans son groupe (institution / ngo). 0 = en haut. Reflète l'ordre d'Amadou — ne pas trier par alphabet.
   */
  order: number;
  /**
   * Optionnel — affiché dans la carte. En attente côté REACT, placeholder initiales sinon.
   */
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Programmes actifs portés par REACT. Sen React est le programme phare (headline).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  slug: string;
  title: string;
  /**
   * Ex. 'Programme phare', 'Programme actif'.
   */
  eyebrow: string;
  /**
   * Une à deux phrases, FR. Verbatim ou quasi-verbatim de la réponse d'Amadou.
   */
  description: string;
  variant: 'headline' | 'active';
  order: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Membres de l'équipe REACT affichés sur /a-propos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  slug: string;
  name: string;
  role: string;
  order: number;
  /**
   * Optionnelle. En attente — placeholder initiales en attendant.
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  body?: T;
  sector?: T;
  writePath?: T;
  sourceUrl?: T;
  publishedAt?: T;
  coverImage?: T;
  commentsEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  file?: T;
  coverImage?: T;
  sector?: T;
  authors?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  publishedAt?: T;
  language?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  youtubeId?: T;
  videoType?: T;
  origin?: T;
  sector?: T;
  subtitlesFr?: T;
  subtitlesWo?: T;
  downloadUrl?: T;
  duration?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  kind?: T;
  description?: T;
  order?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  eyebrow?: T;
  description?: T;
  variant?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  role?: T;
  order?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header".
 */
export interface SiteHeader {
  id: number;
  siteTitle: string;
  /**
   * Short FR phrase shown alongside the site title in the header.
   */
  tagline?: string | null;
  navItems?:
    | {
        label: string;
        labelEn?: string | null;
        /**
         * Path relative to root (e.g. /secteurs) or full URL for external links.
         */
        href: string;
        /**
         * Open in a new tab and add rel=noopener.
         */
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer".
 */
export interface SiteFooter {
  id: number;
  copyrightText: string;
  /**
   * Short FR blurb shown alongside the copyright in the footer.
   */
  description?: string | null;
  legalNavItems?:
    | {
        label: string;
        labelEn?: string | null;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactEmail?: string | null;
  /**
   * Free-form address (e.g. Sacrée Coeur 3 Lot N° 128/B, Dakar).
   */
  contactAddress?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'linkedin' | 'youtube' | 'whatsapp' | 'facebook' | 'x' | 'tiktok';
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  email: string;
  /**
   * Format E.164 sans séparateurs — ex. +221773213955. Utilisé pour les liens wa.me / tel:.
   */
  phoneE164: string;
  /**
   * Format avec séparateurs — ex. '+221 77 321 39 55'.
   */
  phoneDisplay: string;
  /**
   * Une ligne par champ. Affichée multi-ligne dans le pied / Contact.
   */
  addressLines: {
    line: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-hero".
 */
export interface HomepageHero {
  id: number;
  /**
   * Texte court en majuscules vertes au-dessus du titre — ex. 'Réseau des Entrepreneurs Actifs'.
   */
  eyebrow: string;
  /**
   * Une à deux phrases — voix de marque verbatim.
   */
  headline: string;
  /**
   * Sous le titre. 2-4 phrases qui posent la mission.
   */
  leadParagraph: string;
  primaryCta: {
    label: string;
    /**
     * Chemin relatif (/inscription) ou URL absolue.
     */
    href: string;
  };
  secondaryCta: {
    label: string;
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header_select".
 */
export interface SiteHeaderSelect<T extends boolean = true> {
  siteTitle?: T;
  tagline?: T;
  navItems?:
    | T
    | {
        label?: T;
        labelEn?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer_select".
 */
export interface SiteFooterSelect<T extends boolean = true> {
  copyrightText?: T;
  description?: T;
  legalNavItems?:
    | T
    | {
        label?: T;
        labelEn?: T;
        href?: T;
        id?: T;
      };
  contactEmail?: T;
  contactAddress?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  email?: T;
  phoneE164?: T;
  phoneDisplay?: T;
  addressLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-hero_select".
 */
export interface HomepageHeroSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  leadParagraph?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}